SkinHealth/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib import admin
from myhome import views
from Data.views import DataHistoryView
from Data.views import APIDataHistoryView

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$', views.MyHomeListView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^myhome/', include('myhome.urls', namespace='myhome')),
    url(r'^Data/history/$', DataHistoryView.as_view(), name='DataHistory_Tvalue'),
    # Raw Data API
    url(r'^api/Data/history/$', APIDataHistoryView.as_view(), name='api-data-history'),
]

myhome/urls.py
from django.conf.urls import url
from . import views

app_name = 'myhome'

urlpatterns = [
    url(r'^index', views.IndexView.as_view(), name='index'),
    url(r'^$', views.MyHomeListView.as_view(), name='myhome'),
    url(r'^testCon$', views.ArdunioConnection, name='connection'),
    url(r'^ReadLong$', views.ArdunioReadLong, name='readlong'),
    url(r'^historyofTvalue', views.History_TvalueView.as_view(), name='historyofTvalue'),
    url(r'^historyofUvalue', views.History_UvalueView.as_view(), name='historyofUvalue'),
    url(r'^historyofHvalue', views.History_HvalueView.as_view(), name='historyofHvalue'),
    url(r'^UV', views.UV_valueView.as_view(), name='uvValue'),

    url(r'^week_Hvalue', views.week_HvalueView.as_view(), name='week_Hvalue'),
    url(r'^week_Tvalue', views.week_TvalueView.as_view(), name='week_Tvalue'),
    url(r'^week_Uvalue', views.week_UvalueView.as_view(), name='week_Uvalue'),

    url(r'^login/$', views.user_login, name="login"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^register/', views.register, name='register'),
    url(r'^info/', views.Userinfo, name='info'),
    url(r'^edit_profile/', views.editprofile, name='edit_profile'),
]

myhome/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.models import AbstractUser

class UserProfile(AbstractUser):
    gender = models.CharField(max_length=6, choices=(("male",u"male"),("female",u"female"),("secret", u"secret")), default="secret")
    email = models.EmailField(null=True, blank=True)
    remarks = models.CharField(max_length=500, null=True, blank=True)
    address = models.CharField(max_length=100, default=u"")



    class Meta(AbstractUser.Meta):
        pass

    def __str__(self):
        return (self.username)


# Create your models here.
class Notification(models.Model):
    title = models.CharField(max_length=50)
    message = models.CharField(max_length=500)


class Seneor(models.Model):
    Tvalue = models.FloatField()
    Hvalue = models.FloatField()
    Uvalue = models.IntegerField(default=0)
    time = models.DateTimeField(default=timezone.now)

myhome/forms.py
from django import forms
from .models import  UserProfile
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = UserProfile
        fields = ("username", "email")

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['username', 'gender', 'address', 'email']

myhome/views.py
from django.core.exceptions import ImproperlyConfigured
from django.views.generic import ListView,TemplateView
from .models import Notification
from django.contrib.auth.mixins import LoginRequiredMixin
import serial
from django.shortcuts import render, get_object_or_404
from myhome.models import Seneor
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
import json
from django.shortcuts import render_to_response
from django.template import RequestContext

from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from .models import UserProfile
from .forms import  RegisterForm, UserInfoForm



# Create your views here.
class MyHomeListView(ListView):
    template_name = 'myhome.html'
    context_object_name = 'notifications'
    # login_url = '/auth/login/'

    def get_queryset(self):
        result = Notification.objects.values()
        return result



class IndexView(TemplateView):
    template_name = 'home.html'




# def ArdunioConnection(request):
#
#      ser = serial.Serial("/dev/cu.usbmodem1421", baudrate=9600)
#
#      while 1:
#          arduinoData = ser.readline().decode('ascii')
#          print(arduinoData)
#          data_display = arduinoData.replace(',', '').strip('\n').strip('\r')
#          print(data_display)
#          Tvalue = float(data_display[:5])
#          Hvalue = float(data_display[5:10])
#          Uvalue = int(data_display[10:])
#          print(Tvalue)
#          print(Hvalue)
#          print(Uvalue)
#
#          data = Seneor.objects.create(Tvalue=Tvalue, Uvalue=Uvalue, Hvalue=Hvalue)
#          data.save()
#
#          if(Uvalue <= 2):
#
#              if(Hvalue <=40):
#                  context = {'UVNote': 'UV value is low. You can go out and have fun!',
#                             'HNote': 'Humidity value is too low for your skin',
#                             'data': data}
#              elif(Hvalue >40 and Hvalue<=60):
#                  context = {'UVNote': 'UV value is low. You can go out and have fun!',
#                             'HNote': 'This is moderate humidity level for your skin. Enjoy your environment!',
#                             'data': data}
#              elif (Hvalue > 60):
#                  context = {'UVNote': 'UV value is low. You can go out and have fun!',
#                            'HNote': 'The humidity level is too high. Higher levels to allow dust mites to grow on skin and trigger for skin allergy.',
#                            'data': data}
#
#          elif(Uvalue > 2 and Uvalue <= 5):
#
#              if (Hvalue <= 40):
#                  context = {'UVNote': 'UV value is moderate. You can go out and fun! But you’d better to use sunscreen(SPF30) or sunglasses to protect your skin from aging causing by UV.',
#                             'HNote': 'Humidity value is too low for your skin',
#                             'data': data}
#              elif (Hvalue > 40 and Hvalue <= 60):
#                  context = {'UVNote': 'UV value is moderate. You can go out and fun! But you’d better to use sunscreen(SPF30) or sunglasses to protect your skin from aging causing by UV.',
#                             'HNote': 'This is moderate humidity level for your skin. Enjoy your environment!',
#                             'data': data}
#              elif (Hvalue > 60):
#                  context = {'UVNote': 'UV value is moderate. You can go out and fun! But you’d better to use sunscreen(SPF30) or sunglasses to protect your skin from aging causing by UV.',
#                             'HNote': 'The humidity level is too high. Higher levels to allow dust mites to grow on skin and trigger for skin allergy.',
#                             'data': data}
#          elif(Uvalue > 5 and Uvalue <= 7):
#
#              if (Hvalue <= 40):
#                  context = {
#                      'UVNote': 'UV value is high. Please use appropriate protection like sunscreen (SPF 50++), sunglasses, sun-protective clothing or slap.',
#                      'HNote': 'Humidity value is too low for your skin',
#                      'data': data}
#              elif (Hvalue > 40 and Hvalue <= 60):
#                  context = {
#                      'UVNote': 'UV value is high. Please use appropriate protection like sunscreen (SPF 50++), sunglasses, sun-protective clothing or slap.',
#                      'HNote': 'This is moderate humidity level for your skin. Enjoy your environment!',
#                      'data': data}
#              elif (Hvalue > 60):
#                  context = {
#                      'UVNote': 'UV value is high. Please use appropriate protection like sunscreen (SPF 50++), sunglasses, sun-protective clothing or slap.',
#                      'HNote': 'The humidity level is too high. Higher levels to allow dust mites to grow on skin and trigger for skin allergy.',
#                      'data': data}
#          elif(Uvalue > 8 and Uvalue <= 10):
#
#              if (Hvalue <= 40):
#                  context = {'UVNote': 'UV value is very high. You’d better stay indoors or use appropriate protection like sunscreen (SPF 50+++), sunglasses, sun-protective clothing or slap.',
#                             'HNote': 'Humidity value is too low for your skin',
#                             'data': data}
#              elif (Hvalue > 40 and Hvalue <= 60):
#                  context = {'UVNote': 'UV value is very high. You’d better stay indoors or use appropriate protection like sunscreen (SPF 50+++), sunglasses, sun-protective clothing or slap.',
#                             'HNote': 'This is moderate humidity level for your skin. Enjoy your environment!',
#                             'data': data}
#              elif (Hvalue > 60):
#                  context = {'UVNote': 'UV value is very high. You’d better stay indoors or use appropriate protection like sunscreen (SPF 50+++), sunglasses, sun-protective clothing or slap.',
#                             'HNote': 'The humidity level is too high. Higher levels to allow dust mites to grow on skin and trigger for skin allergy.',
#                             'data': data}
#          else:
#
#              if (Hvalue <= 40):
#                  context = {'UVNote': 'UV value is extremely strong. You should better stay indoors. The sun ultraviolet (UV) radiation is the major cause of skin cancer and cause of skin aging',
#                             'HNote': 'Humidity value is too low for your skin',
#                             'data': data}
#              elif (Hvalue > 40 and Hvalue <= 60):
#                  context = {'UVNote': 'UV value is extremely strong. You should better stay indoors. The sun ultraviolet (UV) radiation is the major cause of skin cancer and cause of skin aging',
#                             'HNote': 'This is moderate humidity level for your skin. Enjoy your environment!',
#                             'data': data}
#              elif (Hvalue > 60):
#                  context = {'UVNote': 'UV value is extremely strong. You should better stay indoors. The sun ultraviolet (UV) radiation is the major cause of skin cancer and cause of skin aging',
#                             'HNote': 'The humidity level is too high. Higher levels to allow dust mites to grow on skin and trigger for skin allergy.',
#                             'data': data}
#
#          break
#
#      ser.close()
#
#      return render(request, 'myhome.html', context)

def ArdunioConnection(request):
    ser = serial.Serial("/dev/cu.usbmodem1411", baudrate=9600)

    while 1:
        arduinoData = ser.readline().decode('ascii')
        print(arduinoData)
        data_display = arduinoData.replace(',', '').strip('\n').strip('\r')
        print(data_display)
        Tvalue = float(data_display[:5])
        Hvalue = float(data_display[5:10])
        Uvalue = int(data_display[10:])
        print(Tvalue)
        print(Hvalue)
        print(Uvalue)

        data = Seneor.objects.create(Tvalue=Tvalue, Uvalue=Uvalue, Hvalue=Hvalue)
        data.save()

        if (Uvalue <= 2):

            if (Hvalue <= 40):
                context = {'UVNote': 'UV value is low. You can go out and have fun!',
                           'HNote': 'Humidity value is too low for your skin',
                           'data': data}
            elif (Hvalue > 40 and Hvalue <= 60):
                context = {'UVNote': 'UV value is low. You can go out and have fun!',
                           'HNote': 'This is moderate humidity level for your skin. Enjoy your environment!',
                           'data': data}
            elif (Hvalue > 60):
                context = {'UVNote': 'UV value is low. You can go out and have fun!',
                           'HNote': 'The humidity level is too high. Higher levels to allow dust mites to grow on skin and trigger for skin allergy.',
                           'data': data}

        elif (Uvalue > 2 and Uvalue <= 5):

            if (Hvalue <= 40):
                context = {
                    'UVNote': 'UV value is moderate. You can go out and fun! But you’d better to use sunscreen(SPF30) or sunglasses to protect your skin from aging causing by UV.',
                    'HNote': 'Humidity value is too low for your skin',
                    'data': data}
            elif (Hvalue > 40 and Hvalue <= 60):
                context = {
                    'UVNote': 'UV value is moderate. You can go out and fun! But you’d better to use sunscreen(SPF30) or sunglasses to protect your skin from aging causing by UV.',
                    'HNote': 'This is moderate humidity level for your skin. Enjoy your environment!',
                    'data': data}
            elif (Hvalue > 60):
                context = {

myhome/templates/TEST.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

myhome/templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>About</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Trendz Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="/static/css/bootstrapn.css" rel='stylesheet' type='text/css' />
<link href="/static/css/stylenew.css" rel='stylesheet' type='text/css' />
<script src="/static/js/jquery-1.11.1.min.js"></script>
<script src="http://d3js.org/d3.v3.min.js"></script>
<!--fonts-->
<link href='#css?family=Raleway:400,200,600,800,900,500' rel='stylesheet' type='text/css'>
<link href='#css?family=Pacifico' rel='stylesheet' type='text/css'>
        <style>
        {% block style %}
        {% endblock %}
    </style>
<!--//fonts-->
</head>
<body>
<!--header-->
<!--banner-->
	<div class="banner" style="background-color:#6CB6B6;"> </div>
	<!---->
	<div class="header">
		<div class="header-top">
			<div class="logo">
				<h1><a href="#">skinhealth</a></h1>
			</div>
			<div class="top-nav">
			        <span class="menu"> </span>
					<ul>
						<li ><a href="{% url 'myhome:myhome' %}"class="scroll" data-hover="HOME" >HOME</a></li>
						<li class="scroll"><a href="{% url 'myhome:historyofUvalue' %}" class="scroll" data-hover="UV">UV</a></li>
						<li><a href="{% url 'myhome:historyofTvalue' %}" class="scroll" data-hover="Temperature">Temperature</a></li>
						<li><a href="{% url 'myhome:historyofHvalue' %}" class="scroll" data-hover="Humidity">Humidity</a></li>
                        <li><a href="{% url 'myhome:info' %}" class="scroll" data-hover="Profile">Profile</a></li>
{#                        <li><a href="{% url 'myhome:edit_profile' %}" class="scroll" data-hover="Edit_ptofile">Edit_ptofile</a></li>#}
{#						<li><a href="{% url "myhome:login" %}" class="scroll" data-hover="Login">Login</a></li>#}
                        <li><a href="{% url 'myhome:logout' %}" class="scroll" data-hover="Logout">Logout</a></li>
{#                        <a class="btn btn-secondary" href="{% url 'myhome:logout' %}" role="button">Logout</a>#}
					</ul>
					<!--script-->
				<script>
					$("span.menu").click(function(){
						$(".top-nav ul").slideToggle(500, function(){
						});
					});
			</script>
				</div>
				<div class="clearfix"> </div>
		</div>
	</div>
	<!--content-->

        <br/>

 {% block main %}


{% endblock %}

<script>
    {% block script %}{% endblock %}
</script>

	<!--footer-->
<div class="container">
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
    <br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
    </div>
	<div class="footer">
		<div class="container">
					 <ul class="social-ic-icons">
						<li class="twitter"><a href="#"><span> </span></a></li>
						<li class="facebook"><a href="#"><span> </span></a></li>
						<li class="gmail"><a href="#"><span> </span></a></li>
					</ul>
					<p class="footer-grid">Copyright &copy; 2017.Elec5622 Group4 All rights reserved.<a target="_blank" href="http://www.moobnn.com/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a> - Skin health<a href="http://www.moobnn.com/" target="_blank" title="模板在线">模板在线</a> <a href="http://guantaow.taobao.com" target="_blank">11</a></p>
		 </div>
	</div>


</body>
</html>

myhome/templates/edit_profile.html
{% extends 'base.html' %}
{% block main %}
<!--header-->

<div class="container">
	<div class="row">



       <div class="col-md-7 ">

<div class="panel panel-default">
  <div class="panel-heading">  <h4 >User Profile</h4></div>
   <div class="panel-body">

    <div class="box box-info">

            <div class="box-body">
                     <div class="col-sm-6">
                     <div  align="center"> <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive">



                     </div>

              <br>

              <!-- /input-group -->
            </div>

            <div class="clearfix"></div>
            <hr style="margin:5px 0 5px 0;">

<form class="form" action="{% url 'myhome:edit_profile' %}" method="post">
 {% csrf_token %}
  {% for field in user_info_form %}

   <h2> {{ field.label_tag }}
    {{ field }}</h2>
    <h2>{{ field.errors }}</h2>
    {% if field.help_text %}
        <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
    {% endif %}
      <br>
  {% endfor %}
  <button type="submit" class="btn btn-primary btn-lg">Confirm</button>
</form>

            </div>
    </div>
   </div>
</div>
       </div>
    </div>

</div>
    <script>
              $(function() {
    $('#profile-image1').on('click', function() {
        $('#profile-image-upload').click();
    });
});
              </script>
{% endblock %}

myhome/templates/historyofHvalue.html
{% extends 'base.html' %}
<style>
    {% block style %}
        .bar{
            fill: steelblue;
        }

        .bar:hover{
            fill: brown;
        }

        .axis {
            font: 10px sans-serif;
        }

        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
    {% endblock %}
</style>

{% block main %}
    <div class="col-xs-8" style="padding: 5px;">
        <svg width="800" height="430" id="chart" ></svg>
    </div>

     <div class="col-xs-4">
         <div class="btn-group" role="group" aria-label="...">
         <a type="button" class="btn btn-default" href="{% url "myhome:historyofHvalue" %}">Day</a>
         <a type="button" class="btn btn-default" href="{% url "myhome:week_Hvalue" %}">Week</a>
    </div>

         <img src="/static/image/advice.png" height="150" width="200">
         <textarea cols="50" rows="10" wrap="hard" readonly="yes">{{ Notification }} </textarea>
    </div>

{% endblock %}
<script>
    {% block script %}

        var endpoint = "../../api/Data/history/";

        $.ajax({
            method: "GET",
            url: endpoint,

            success: function (data) {

                // var margin = {top: 20, right: 20, bottom: 70, left: 40},
                //     width = 600 - margin.left - margin.right,
                //     height = 300 - margin.top - margin.bottom;
                var margin = {top: 30, right: 20, bottom: 50, left: 100},
                    width = parseInt(d3.select("#chart").style("width")) - margin.left - margin.right,
                    height = parseInt(d3.select("#chart").style("height")) - margin.top - margin.bottom;


                // set the ranges
                var x = d3.scale.ordinal().rangeRoundBands([0, width], .05);

                var y = d3.scale.linear().range([height, 0]);

                // define the axis
                var xAxis = d3.svg.axis()
                    .scale(x)
                    .orient("bottom")


                var yAxis = d3.svg.axis()
                    .scale(y)
                    .orient("left")
                    .ticks(10);


                // add the SVG element
                var svg = d3.select("#chart").append("svg")
                    .attr("width", width + margin.left + margin.right)
                    .attr("height", height + margin.top + margin.bottom)
                    .append("g")
                    .attr("transform",
                        "translate(" + margin.left + "," + margin.top + ")");


                // load the data
                d3.json(endpoint, function(error, data) {

                  function draw_graph(){
                    data.forEach(function(d) {
                        d.id = d.id;
                        d.Tvalue = +d.Tvalue;
                    });

                    // scale the range of the data
                    x.domain(data.map(function(d) { return d.id; }));
                    y.domain([0, d3.max(data, function(d) { return d.Hvalue; })]);

                    // add axis
                    svg.append("g")
                        .attr("class", "x axis")
                        .attr("transform", "translate(0," + height + ")")
                        .call(xAxis)
                        .selectAll("text")
                        .style("text-anchor", "end")
                        .attr("dx", "-.8em")
                        .attr("dy", "-.55em")
                        .attr("transform", "rotate(-90)" );

                    svg.append("g")
                        .attr("class", "y axis")
                        .call(yAxis)
                        .append("text")
                        .attr("font-weight", "bold")
                        .attr("fill", "#000")
                        .attr("transform", "rotate(-90)")
                        .attr("y", -50)
                        .attr("dy", ".71em")
                        .style("font-size","15px")
                        .style("text-anchor", "end")
                        .text("Average value/hour");

                    svg.append("g")
                        .attr("class", "y axis")
                        .call(yAxis)
                        .append("text")
                        .attr("font-weight", "bold")
                        .attr("fill", "#000")
                        .attr("transform", "rotate(-0)")
                        .attr("y", -30)
                        .attr("x", 390)
                        .attr("dy", ".71em")
                        .style("font-size","15px")
                        .style("text-anchor", "end")
                        .text("Humid Value");

                     svg.append("g")
                        .attr("class", "y axis")
                        .call(yAxis)
                        .append("text")
                        .attr("font-weight", "bold")
                        .attr("fill", "#000")
                        .attr("transform", "rotate(-0)")
                        .attr("y", 380)
                        .attr("x", 50)
                        .attr("dy", ".71em")
                        .style("font-size","15px")
                        .style("text-anchor", "end")
                        .text("Past 24 Hours");


                    // Add bar chart
                    svg.selectAll("bar")
                        .data(data)
                        .enter().append("rect")
                        .attr("class", "bar")
                        .attr("x", function(d) { return x(d.id); })
                        .attr("width", x.rangeBand())
                        .attr("y", function(d) { return y(d.Hvalue); })
                        .attr("height", function(d) { return height - y(d.Hvalue); });
                    };

                    draw_graph.call(svg, {
                    data:data
                  });
                });
            }});
    {% endblock %}
</script>

myhome/templates/historyofUvalue.html
{% extends 'base.html' %}
<style>
    {% block style %}
        .bar{
            fill: steelblue;
        }

        .bar:hover{
            fill: brown;
        }

        .axis {
            font: 10px sans-serif;
        }

        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
    {% endblock %}
</style>

{% block main %}
    <div class="col-xs-8" style="padding: 5px;">
        <svg width="800" height="430" id="chart" ></svg>
    </div>

    <div class="col-xs-4">
         <div class="btn-group" role="group" aria-label="...">
         <a type="button" class="btn btn-default" href="{% url "myhome:historyofUvalue" %}">Day</a>
         <a type="button" class="btn btn-default" href="{% url "myhome:week_Uvalue" %}">Week</a>
    </div>

         <img src="/static/image/advice.png" height="150" width="200">
         <textarea cols="50" rows="10" wrap="hard" readonly="yes">{{ Notification }} </textarea>
    </div>

{% endblock %}
<script>
    {% block script %}

        var endpoint = "../../api/Data/history/";

        $.ajax({
            method: "GET",
            url: endpoint,

            success: function (data) {

                // var margin = {top: 20, right: 20, bottom: 70, left: 40},
                //     width = 600 - margin.left - margin.right,
                //     height = 300 - margin.top - margin.bottom;
                var margin = {top: 30, right: 20, bottom: 50, left: 100},
                    width = parseInt(d3.select("#chart").style("width")) - margin.left - margin.right,
                    height = parseInt(d3.select("#chart").style("height")) - margin.top - margin.bottom;


// set the ranges
                var x = d3.scale.ordinal().rangeRoundBands([0, width], .05);

                var y = d3.scale.linear().range([height, 0]);

// define the axis
                var xAxis = d3.svg.axis()
                    .scale(x)
                    .orient("bottom")


                var yAxis = d3.svg.axis()
                    .scale(y)
                    .orient("left")
                    .ticks(10);


// add the SVG element
                var svg = d3.select("#chart").append("svg")
                    .attr("width", width + margin.left + margin.right)
                    .attr("height", height + margin.top + margin.bottom)
                    .append("g")
                    .attr("transform",
                        "translate(" + margin.left + "," + margin.top + ")");


// load the data
                d3.json(endpoint, function(error, data) {

                 function draw_graph(){
                    data.forEach(function(d) {
                        d.id = d.id;
                        d.Uvalue = +d.Uvalue;
                    });

                    // scale the range of the data
                    x.domain(data.map(function(d) { return d.id; }));
                    y.domain([0, d3.max(data, function(d) { return d.Uvalue; })]);

                    // add axis
                    svg.append("g")
                        .attr("class", "x axis")
                        .attr("transform", "translate(0," + height + ")")
                        .call(xAxis)
                        .selectAll("text")
                        .style("text-anchor", "end")
                        .attr("dx", "-.8em")
                        .attr("dy", "-.55em")
                        .attr("transform", "rotate(-90)" );

                  svg.append("g")
                        .attr("class", "y axis")
                        //.call(yAxis)
                        .append("text")
                        .attr("font-weight", "bold")
                        .attr("fill", "#000")
                        .attr("transform", "rotate(-90)")
                        .attr("y", -50)
                        .attr("dy", ".71em")
                        .style("font-size","15px")
                        .style("text-anchor", "end")
                        .text("Average value/hour");

                  svg.append("g")
                        .attr("class", "y axis")
                        //.call(yAxis)
                        .append("text")
                        .attr("font-weight", "bold")
                        .attr("fill", "#000")
                        .attr("transform", "rotate(-0)")
                        .attr("y", -30)
                        .attr("x", 390)
                        .attr("dy", ".71em")
                        .style("font-size","15px")
                        .style("text-anchor", "end")
                        .text("UV Value");

                    svg.append("g")
                        .attr("class", "y axis")
                        .call(yAxis)
                        .append("text")
                        .attr("font-weight", "bold")
                        .attr("fill", "#000")
                        .attr("transform", "rotate(-0)")
                        .attr("y", 380)
                        .attr("x", 50)
                        .attr("dy", ".71em")
                        .style("font-size","15px")
                        .style("text-anchor", "end")
                        .text("Past 24 Hours");


                    // Add bar chart
                    svg.selectAll("bar")
                        .data(data)
                        .enter().append("rect")
                        .attr("class", "bar")
                        .attr("x", function(d) { return x(d.id); })
                        .attr("width", x.rangeBand())
                        .attr("y", function(d) { return y(d.Uvalue); })
                        .attr("height", function(d) { return height - y(d.Uvalue); });
                    }


                    draw_graph.call(svg, {
                      data:data
                    });

                });


            }});
    {% endblock %}
</script>

myhome/templates/notifications.html
<form action="/myhome/testCon" method="POST">
    <input id="submit" type="button" value="Click" />
</form>
    <h1>{{ data.Uvalue }}</h1>
    <h1>{{ data.Hvalue }}</h1>
    <h1>{{ data.Tvalue }}</h1>
    